[build]
  command = "npm run build:production"
  publish = "dist/public-site/browser"

[[plugins]]
  package = "@netlify/angular-runtime"

[[redirects]]
  from = "/"
  to = "/bg/"
  status = 302

[[redirects]]
  from = "/bg/*"
  to = "/bg/index.csr.html"
  status = 200

[[redirects]]
  from = "/en/*"
  to = "/en/index.html"
  status = 200

[[redirects]]
  from = "/bg"
  to = "/bg/"
  status = 302

[[redirects]]
  from = "/en"
  to = "/en/"
  status = 302

[[redirects]]
  from = "/*"
  to = "/bg/"
  status = 302