name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:

  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
      - name: Install dependencies and build project
        run: | # angular is my folder in the repository root project where I store front-end code (if your angular project and its package.json are located in the root folder of the GitHub repository remove "cd angular"
          # cd angular
          npm ci
          npm run build
      - name: Ensure index.html exists in /browser
        run: | # You can put any content inside the index.html, but without this file Deployment to Azure won't succeed
          mkdir -p dist/denix-labs-public-site/browser
          cp public/fonts dist/denix-labs-public-site/browser
          cp -R public/fonts dist/denix-labs-public-site/browser/fonts
          cp -R public/js dist/denix-labs-public-site/browser/js
          cd dist/denix-labs-public-site/browser
          echo "<html><body><h1>Hello!</h1></body></html>" > index.html
          
      - name: Copy staticwebapp.config.json to /browser folder
        run: | # angular is my folder in the repository root project where I store front-end code
          # cd angular
          cp staticwebapp.config.json dist/denix-labs-public-site/browser

      - name: Deploy
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_POND_08166FB1E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "./dist/denix-labs-public-site/browser" # App source code path
          github_id_token: ${{ steps.idtoken.outputs.result }}
          skip_app_build: true  # tell the azure not to build the app for us, we have already done this manually using Node
          ###### End of Repository/Build Configurations ######
      # - name: Build And Deploy
      #   id: builddeploy
      #   uses: Azure/static-web-apps-deploy@v1
      #   with:
      #     azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_POND_08166FB1E }}
      #     repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
      #     action: "upload"
      #     ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
      #     # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
      #     app_location: "/" # App source code path
      #     api_location: "" # Api source code path - optional
      #     # output_location: "dist/admin-frontend" # Built app content directory - optional
      #     ###### End of Repository/Build Configurations ######
  

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_POND_08166FB1E }}
          action: "close"
